name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - /AzDevOps/windows/install-agent.ps1
pr:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - /AzDevOps/windows/install-agent.ps1
 
resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
steps:
- powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhss"))"
  displayName: Set Build Name for Non-PR
  condition: ne(variables['Build.Reason'], 'PullRequest')

- powershell:  Install-module pester -Scope CurrentUser -Force -SkipPublisherCheck
  displayName: Install Pester
  condition: succeededOrFailed()

- powershell: |
   $results = Invoke-Pester -OutputFile test-results.xml -OutputFormat NUnitXml -PassThru
   
   if(!$results -or !$results.TotalCount -or $results.FailedCount -gt 0)
   {
       throw "tests failed"
   } 
  displayName: Run Unit tests

- task: PublishTestResults@2
  displayName: Publish Test Results **/TEST-*.xml

